apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "movies-api.fullname" . }}
  labels:
    {{- include "movies-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "movies-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.endpoint }}
      interval: 10s