keycloak:
  image:
    tag: 10.0.2
  username: admin
  password: admin
  service:
    type: NodePort
  persistence:
    dbVendor: mysql
    dbHost: my-mysql
    dbPort: 3306
    dbName: keycloak
    dbUser: keycloak
    dbPassword: keycloak
  extraEnv: |
    - name: JDBC_PARAMS
      value: useSSL=false
